### ISSUE TITLE
int8 model doesn't work

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [lewes6369/TensorRT-Yolov3#5]
Thanks for your brilliant work!! I try a yolov3 caffemodel cloned from github. fp18 fp32 works, but is poor precesion, I don't know why, so where can I get your yolo caffemodel? many thanks    

And when I ran the int8 mode , it occurs:
load batch 0 to 0 
ERROR: engine.cpp(404) - Cuda Error in commonEmitTensor:11
ERROR:Failure while trying to emit debug blob.
engine.cpp(404) -Cuda Error in commonEmitTensor: 11
....
...
...
terminate called after throwing an instance of 'nvinfer1::CudaError'
    what(): std::exception
Aborted(core dumped)

my cuda is 10.0  tensorRT5.0  can you give me some suggestion?    thanks a lot!!!!!

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
sorry i found the reason.....

**Comment by abhigoku10** [comment]
@Yuuuuuuuuuuuuuuuuuummy  were you able to save the yolov3 into int8 weights

**Comment by ColinPeeris** [comment]
@Yuuuuuuuuuuuuuuuuuummy 
I'm getting the same issue trying to use the int8 calibration. 

[E] [TRT] C:\p4sw\sw\gpgpu\MachineLearning\DIT\release\5.1\engine\engine.cpp (572) - Cuda Error in nvinfer1::rt::ExecutionContext::commonEmitTensor: 11 (invalid argument)
[E] [TRT] Failure while trying to emit debug blob.

Could you share how you resolved your issue?

Thanks.

Colin
